### PR TITLE
Pull Upstream from Zcash 1.0.3

### PR DESCRIPTION
**Pull request by heyrhett**
To test:
git clone git@github.com:z-classic/zclassic.git
git checkout -b zcash-master-103
Build
./zcutil/build.sh -j$(nproc)
fetch key
./zcutil/fetch-params.sh
Run
./src/zcashd

### CODE REVIEW

**Comment by hairetikos** [comment]
Builds fine for me.  zcashd works and mines.

Ubuntu 15.10, Kernel 4.2.0-42-generic

**Comment by aayanl** [comment]
Gtest ran fine, I was able to send a transaction and have it confirm

**Comment by aayanl** [comment]
#28

**Comment by aayanl** [comment]
Passed and worked

PASS: test/test_bitcoin
PASS: zcash-gtest

**Comment by cronicc** [comment]
./zcutil/build.sh OK
./qa/zcash/full-test-suite.sh PASSED
sync to network OK
txindex reindex OK
send/receive transparent OK

**Pull request merged**
