### PR TITLE
Significant updates enabling explorer, includes mempool and address indexing methods

### PR DESCRIPTION
**Pull request by ch4ot1c**
This code needed to be migrated from Zcash 1.0.13 in order to index versions of Zclassic past 1.0.4. By 'explorers', we mean Insight-UI and Insight-API (from johandjoz/insight-ui-zclassic)

### CODE REVIEW

**Comment by heyrhett** [comment]
Anyone care to review this?

**Comment by ch4ot1c** [comment]
In BTCP, we've used it as a separate branch and an analogous release ('indexing-enabled'); kept unmerged.

**Comment by ch4ot1c** [comment]
- https://github.com/trezor/hd-wallet
- https://github.com/bitcoinjs/indexd

seem to be more future-proof approaches, per the discussion here:
https://github.com/bitcoin/bitcoin/pull/10370

**Comment by nimbosa** [comment]
Hi all, looks like @TheTrunk just contributed a cleaner implementation here: https://github.com/z-classic/zclassic/pull/182.

It will be a few days before I can properly check it out and maybe compare the two?

**Comment by nimbosa** [comment]
@ch4ot1c one question, do you know what was the motivation behind the change in file permissions to make them all executable? was it deliberate / necessary?

**Comment by nimbosa** [comment]
keep separate for now

**Pull request closed without merging**
