### PR TITLE
Add replay protection. Bugfix.

### PR DESCRIPTION
**Pull request by tarrenj**
As requested by @f1npunk on ZEN slack.  Request related from Rhett.

### CODE REVIEW

**Comment by heyrhett** [comment]
Can we get a more descriptive comment, please?

**Comment by finpunk** [comment]
This fix implements minimalist OP_CHECKBLOCKATHEIGHT protection that prevents accepting transactions from ZEN to ZCL mempool. It is a corrected replay implementation from what is currently active on ZCL and prevents all types of replays while maintaining backward compatibility of all utxo.

**Comment by aayanl** [comment]
ACK on the changes but I'm wondering why is standard.cpp added to zcash-gtest?

**Pull request merged**
