### PR TITLE
BIP Implementation for TX Replay Protection and BIP 9 implementation 

### PR DESCRIPTION
**Pull request by joshuayabut**
Ready for review.

### CODE REVIEW

**Comment by joshuayabut** [comment]
The above code is based on this BIP: https://github.com/luke-jr/bips/blob/bip-noreplay/bip-noreplay.mediawiki

**Relative OP_CHECKBLOCKATHEIGHT lookups will not be supported in this implementation due to block lookup ambiguities**

**Comment by joshuayabut** [comment]
Ok time to deploy the BIP9 softfork onto some of the testnet infrastructure!

**Comment by aayanl** [comment]
it reached the timeout

**Comment by aayanl** [comment]
ill increase it

**Comment by aayanl** [comment]
tests passed okay, not sure what the shelljs error is though

**Pull request merged**
