### PR TITLE
Revert transaction replay protection and BIP9 implementation

### PR DESCRIPTION
**Pull request by joshuayabut**
This removes transaction replay protection and the BIP9 implementation from Zclassic in order to make it a 1:1 clone of Zcash.

### CODE REVIEW

**Comment by heyrhett** [comment]
Removing ZEN replay protection from ZCL actually helps the ZEN team properly implement replay protection from their side.  Also, it keeps ZCL closer to mirroring Zcash minus the dev founder reward, which is the intention of the ZCL project.

**Comment by aayanl** [comment]
The checkpoint code shouldn't be reverted

**Comment by joshuayabut** [comment]
That checkpoint code was inserted as an additional method to mitigate the risk of transaction replay attacks.

**Comment by heyrhett** [comment]
Checkpoints is a separate issue.  It's good to have a recent checkpoint updated on master though as we do updates.

**Comment by aayanl** [comment]
Ok that's fine, we can add that back into a new pr

**Comment by aayanl** [comment]
ACK from my side

**Pull request merged**
