### PR TITLE
Bitcore integration

### PR DESCRIPTION
**Pull request by TheTrunk**
This is a proper Bitcore integration into zclassic codebase.

### CODE REVIEW

**Comment by TheTrunk** [comment]
Ouch I just noticed that there already is a PR for this. Whups. At least this one is cleaner and does not change file permissions

**Comment by nimbosa** [comment]
Hi, thanks for this contribution @TheTrunk, is this based on updated bitcore patches here https://github.com/bitcoin/bitcoin/pull/10370?

**Comment by TheTrunk** [comment]
Hi, It is the same integration as is for example in zelcash, hush, zcash which is based on the original bitcore integration by satoshilabs(?). It is possible that the referenced PR on bitcoin contains some additional patches but since its a different codebase it is a bit hard to compere. I believe bitcoin actually uses bcoin in their insight explorers. This integration is present in a daemon which powers following zclassic explorer: https://explorer.zcl.zeltrez.io .

**Comment by nimbosa** [comment]
Uhmm.. Alright, do you have a link to the original source of this particular implementation? I will be checking this and the older PR, and maybe we will need to rebase some changes as we are merging PRs roughly in chronological order. Right now, the earlier implementation lives on a completely separate branch and using a separate build.  I am looking into unifying them if possible and convenient.

Again, many thanks @TheTrunk. :)

**Comment by nimbosa** [comment]
keep on separate branch for now: https://github.com/z-classic/zclassic/tree/improvement/explorer

**Pull request closed without merging**
